### ISSUE TITLE
Add post build hook

### ISSUE THREAD

**Issue by rhcarvalho** [openshift/dancer-ex#29]
Add an example build hook to run unit tests as part of the build.

:thought_balloon: I tried doing so myself but couldn't get it working without friction, so deferring it for later or someone else.

The hook shall be added to the BuildConfigs of our templates:

``` diff
+        "postCommit": {
+          "script": "perl -Iextlib/lib/perl5 t/*"
+        }
```

I am not sure about the right one-liner to run unit tests.

**Comment by tommybutler** [comment]
Failed to build on openshift dev preview just now.  

In project dancertest on server https://api.preview.openshift.com:443

http://dancer-mysql-example-dancertest.44fs.preview.openshiftapps.com (svc/dancer-mysql-example)
  dc/dancer-mysql-example deploys istag/dancer-mysql-example:latest <-
    bc/dancer-mysql-example source builds https://github.com/dfwperl/dancer-ex.git on openshift/perl:5.20 
      build #1 failed about a minute ago - b0f9889: Merge pull request #48 from luciddreamz/master (Ben Parees <bparees@users.noreply.github.com>)
    deployment #1 waiting on image or update

svc/database - 172.30.207.143:3306
  dc/database deploys openshift/mysql:5.6 
    deployment #1 running for 6 minutes - 1 pod

Errors:
  * build/dancer-mysql-example-1 has failed.
    try: Inspect the build failure with 'oc logs -f bc/dancer-mysql-example'
Warnings:
  * The image trigger for dc/dancer-mysql-example will have no effect until istag/dancer-mysql-example:latest is imported or created by a build.
